import type { Metadata } from 'next'
import { getSettings } from '@/lib/actions/settings'

export async function generateMetadata() {
  const settings = await getSettings()
  return {
    title: settings.siteTitle || 'Create Next App',
    description: settings.description || 'Generated by create next app',
    keywords: settings.keywords || '',
  }
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return <>{children}</>
}
